"""Separate live catalog presence from verified generation access

Revision ID: 444cda8f1d44
Revises: 3485dbc0c4b1
"""

import sqlalchemy as sa
from alembic import op

revision = "444cda8f1d44"
down_revision = "3485dbc0c4b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "models",
        sa.Column(
            "catalog_present", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.alter_column("models", "catalog_present", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "catalog_present")
    # ### end Alembic commands ###
